spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/books

  liquibase:
    change-log: classpath:/db/changelog/master.xml
